Controllers/ContactController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using NICTProject.Data.StoreProcedure;
using NICTProject.Services;
using NICTProject.ViewModel;

namespace NICTProject.Controllers
{
    public class ContactController : Controller
    {
        private readonly IDapperServices _idapperservices;

        public ContactController(IDapperServices idapperServices)
        {
            _idapperservices = idapperServices;
        }
        public IActionResult Index()
        {
            HomePageViewModel ViewModelHomePage = new HomePageViewModel();
            ViewModelHomePage.News = _idapperservices.GetNewsAndEvents(new GetEvents() { });
            return View(ViewModelHomePage);
        }

        public IActionResult Inquiry()
        {
            return View();
        }
    }
}

Controllers/GovtProjectController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using NICTProject.Data.StoreProcedure;
using NICTProject.Services;
using NICTProject.ViewModel;

namespace NICTProject.Controllers
{
    public class GovtProjectController : Controller
    {
        private readonly IDapperServices _idapperservices;

        public GovtProjectController(IDapperServices idapperServices)
        {
            _idapperservices = idapperServices;
        }
        public IActionResult Index()
        {
            HomePageViewModel ViewModelHomePage = new HomePageViewModel();
            ViewModelHomePage.News = _idapperservices.GetNewsAndEvents(new GetEvents() { });
            return View(ViewModelHomePage);
        }
    }
}

Controllers/OurCenterController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using NICTProject.Data.StoreProcedure;
using NICTProject.Services;
using NICTProject.ViewModel;

namespace NICTProject.Controllers
{
    public class OurCenterController : Controller
    {
        private readonly IDapperServices _idapperservices;

        public OurCenterController(IDapperServices idapperServices)
        {
            _idapperservices = idapperServices;
        }
        public IActionResult Index()
        {
            HomePageViewModel ViewModelHomePage = new HomePageViewModel();
            ViewModelHomePage.News = _idapperservices.GetNewsAndEvents(new GetEvents() { });
            return View(ViewModelHomePage);
        }
    }
}

Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using NICTProject.Data.StoreProcedure;
using NICTProject.Services;
using NICTProject.ViewModel;

namespace NICTProject.Controllers
{
    public class UserController : Controller
    {
        private readonly IDapperServices _idapperservices;

        public UserController(IDapperServices idapperServices)
        {
            _idapperservices = idapperServices;
        }
        public IActionResult Login()
        {
            HomePageViewModel ViewModelHomePage = new HomePageViewModel();
            ViewModelHomePage.News = _idapperservices.GetNewsAndEvents(new GetEvents() { });
            return View(ViewModelHomePage);
        }
        
        public IActionResult Exam()
        {
            HomePageViewModel ViewModelHomePage = new HomePageViewModel();
            ViewModelHomePage.News = _idapperservices.GetNewsAndEvents(new GetEvents() { });
            return View(ViewModelHomePage);
        }

    }
}

Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <title>@ViewData["Title"] Krishna Institute</title>

    <link href="https://fonts.googleapis.com/css?family=Work+Sans:100,200,300,400,500,600,700,800,900" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Fredericka+the+Great" rel="stylesheet">

    <link rel="stylesheet" href="@Url.Content("~/css/open-iconic-bootstrap.min.css")">
    <link rel="stylesheet" href="@Url.Content("~/css/animate.css")">

    <link rel="stylesheet" href="@Url.Content("~/css/owl.carousel.min.css")">
    <link rel="stylesheet" href="@Url.Content("~/css/owl.theme.default.min.css")">
    <link rel="stylesheet" href="@Url.Content("~/css/magnific-popup.css")">

    <link rel="stylesheet" href="@Url.Content("~/css/aos.css")">

    <link rel="stylesheet" href="@Url.Content("~/css/ionicons.min.css")">

    <link rel="stylesheet" href="@Url.Content("~/css/flaticon.css")">
    <link rel="stylesheet" href="@Url.Content("~/css/icomoon.css")">
    <link rel="stylesheet" href="@Url.Content("~/css/style.css")">

    @*<link rel="stylesheet" href="@Url.Content("~/lib/bootstrap/dist/css/bootstrap.min.css")" />
        <link rel="stylesheet" href="@Url.Content("~/css/site.css")" />*@
</head>
<body>

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark ftco_navbar ftco-navbar-light" id="ftco-navbar">
        <div class="container d-flex align-items-center">
            <a class="navbar-brand" href="/" style="display: flex; flex-direction: row;">
                <img src="@Url.Content("~/images/logo.png")" class="ftco-animate" alt="Girl in a jacket" style="height: 80px; width: 80px;">
                <div class="pt-2 pl-2 mt-0 heading-section ftco-animate">
                    <h2 class="mb-0" style="font-size: 12px; color: #00266B;"><span>National</span></h2>
                    <h2 class="mb-0" style="font-size: 12px; color: #00266B;"><span>Institute of</span></h2>
                    <h2 class="mb-0" style="font-size: 12px; color: #00266B;"><span>Computer</span> </h2>
                    <h2 class="mb-0" style="font-size: 12px; color: #00266B;"><span>Technology</span> </h2>
                </div>
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#ftco-nav" aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="oi oi-menu"></span> Menu
            </button>
            <div class="collapse navbar-collapse" id="ftco-nav">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item active"><a href="/" class="nav-link pl-0">Logout</a></li>
                </ul>
            </div>
        </div>
    </nav>

    @RenderBody()
    <partial name="_Footer" />

    <!-- loader -->
    <div id="ftco-loader" class="show fullscreen"><svg class="circular" width="48px" height="48px"><circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee" /><circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10" stroke="#F96D00" /></svg></div>

    <script src="@Url.Content("~/js/jquery.min.js")"></script>
    <script src="@Url.Content("~/js/jquery-migrate-3.0.1.min.js")"></script>
    <script src="@Url.Content("~/js/popper.min.js")"></script>
    <script src="@Url.Content("~/js/bootstrap.min.js")"></script>
    <script src="@Url.Content("~/js/jquery.easing.1.3.js")"></script>
    <script src="@Url.Content("~/js/jquery.waypoints.min.js")"></script>
    <script src="@Url.Content("~/js/jquery.stellar.min.js")"></script>
    <script src="@Url.Content("~/js/owl.carousel.min.js")"></script>
    <script src="@Url.Content("~/js/jquery.magnific-popup.min.js")"></script>
    <script src="@Url.Content("~/js/aos.js")"></script>
    <script src="@Url.Content("~/js/jquery.animateNumber.min.js")"></script>
    <script src="@Url.Content("~/js/scrollax.min.js")"></script>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBVWaKrjvy3MaE7SQ74_uJiULgl1JY0H2s&sensor=false"></script>
    <script src="@Url.Content("~/js/google-map.js")"></script>
    <script src="@Url.Content("~/js/main.js")"></script>

    @*<script src="@Url.Content("~/lib/jquery/dist/jquery.min.js")"></script>
        <script src="@Url.Content("~/lib/bootstrap/dist/js/bootstrap.bundle.min.js")"></script>
        <script src="@Url.Content("~/js/site.js")" asp-append-version="true"></script>*@
    @RenderSection("Scripts", required: false)
</body>
</html>

Views/Shared/_Footer.cshtml
@using NICTProject.ViewModel;
@model HomePageViewModel

<footer class="ftco-footer ftco-bg-dark ftco-section pb-0 pt-6">
    <div class="container mb-0">
        <div class="row mb-2">
            <div class="col-md-6 col-lg-3">
                <div class="ftco-footer-widget mb-5">
                    <h2 class="ftco-heading-2  mb-3">Have a Questions?</h2>
                    <div class="block-23 mb-3">
                        <ul>
                            <li><span class="icon icon-map-marker"></span><span class="text">21,Siddeshwer Shopping Center, Opp.Karan Kamlesh Party Plot, Nigam Road, Ghodasar Ahmedabad-380050 , Gujarat.</span></li>
                            <li><a href="#"><span class="icon icon-phone"></span><span class="text">9725025085</span></a></li>
                            <li><a href="#"><span class="icon icon-envelope"></span><span class="text">vipul_patel_krishna@yahoo.co.in</span></a></li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="col-md-6 col-lg-4">
                <div class="ftco-footer-widget mb-3">
                    <h2 class="ftco-heading-2  mb-3">News</h2>
                    <div class="block-21 mb-3 d-flex">
                        <div class="text" style="width: 100%;">
                            <marquee behavior="scroll" direction="up" scrollamount="2">
                                @*@foreach (NewsAndEvent news in Model.News)
                                {
                                    <h3 class="heading"><a href="#">@news.title</a></h3>
                                    <div class="meta">
                                        <div><a href="#"><span class="icon-calendar">@news.eventdate Dec 25, 2018</span></a></div>
                                        <div><span class="icon-person">@news.eventshortdesc Admin</span></div>
                                        <div><span class="icon-chat"> 19</span></div>
                                    </div>
                                }*@
                            </marquee>
                        </div>
                    </div>
                </div>
                <div class="ftco-footer-widget mb-3">
                    <h2 class="ftco-heading-2 mb-3">Events</h2>
                    <div class="block-21 mb-4 d-flex">
                        <div class="text" style="width: 100%;">
                            <marquee behavior="scroll" direction="up" scrollamount="2">
                                <h3 class="heading"><a href="#">Even the all-powerful Pointing has no control about</a></h3>
                                <div class="meta">
                                    <div><a href="#"><span class="icon-calendar"></span> Dec 25, 2018</a></div>
                                    <div><a href="#"><span class="icon-person"></span> Admin</a></div>
                                    <div><a href="#"><span class="icon-chat"></span> 19</a></div>
                                </div>
                            </marquee>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-6 col-lg-2">
                <div class="ftco-footer-widget mb-3 ml-md-4">
                    <h2 class="ftco-heading-2  mb-3">Links</h2>
                    <ul class="list-unstyled">
                        <li><a href="@Url.Action("Index","Home")"><span class="ion-ios-arrow-round-forward mr-2"></span>Home</a></li>
                        <li><a href="@Url.Action("GolsAirms","Home")"><span class="ion-ios-arrow-round-forward mr-2"></span>Goal & Amis</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-md-6 col-lg-3">
                <div class="ftco-footer-widget mb-3">
                    <h2 class="ftco-heading-2  mb-3">Subscribe Us!</h2>
                    <form action="#" class="subscribe-form">
                        <div class="form-group">
                            <input type="text" class="form-control mb-2 text-center" placeholder="Enter email address">
                            <input type="submit" value="Subscribe" class="form-control submit px-3">
                        </div>
                    </form>
                </div>
                <div class="ftco-footer-widget mb-3">
                    <h2 class="ftco-heading-2 mb-3">Connect With Us</h2>
                    <ul class="ftco-footer-social list-unstyled float-md-left float-lf">
                        <li class="ftco-animate"><a href="#"><span class="icon-twitter"></span></a></li>
                        <li class="ftco-animate"><a href="#"><span class="icon-facebook"></span></a></li>
                        <li class="ftco-animate"><a href="#"><span class="icon-instagram"></span></a></li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12 text-center">
                <p> Copyright &copy;2010, Krishna Infotech  </p>
            </div>
        </div>
    </div>
</footer>

Views/Shared/_Header.cshtml
<div class="py-2 bg-primary">
    <div class="container">
        <div class="row no-gutters d-flex align-items-start align-items-center px-3 px-md-0">
            <div class="col-lg-12 d-block">
                <div class="row d-flex">
                    <!-- <div class="col-md pr-4 d-flex topper align-items-center">
                        <div class="icon bg-fifth mr-2 d-flex justify-content-center align-items-center"><span class="icon-map"></span></div>
                        <span class="text">National Institute of Computer Technology</span>
                    </div> -->
                    <div class="col-md pr-4 d-flex topper align-items-center">
                        <div class="icon bg-tertiary mr-2 d-flex justify-content-center align-items-center"><span class="icon-phone2"></span></div>
                        <span class="text">Franchisee Inquiry :- 9725025085</span>
                    </div>
                    <div class="col-md pr-4 d-flex topper align-items-center">
                        <div class="icon bg-tertiary mr-2 d-flex justify-content-center align-items-center"><span class="icon-phone2"></span></div>
                        <span class="text">For Certification Inquiry :- 9725025085</span>
                    </div>
                    <div class="col-md-1 pr-4 d-flex topper align-items-center">
                        <button type="button" class="btn btn-success mr-2 btn-sm"><a href="@Url.Action("Login","User")" style="color:aliceblue;">Login</a></button>
                        <button type="button" class="btn btn-success  btn-sm"><a href="@Url.Action("Exam","User")" style="color:aliceblue;">Exam</a></button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark ftco_navbar ftco-navbar-light" id="ftco-navbar">
    <div class="container d-flex align-items-center">
        <a class="navbar-brand" href="/" style="display: flex; flex-direction: row;">
            <img src="@Url.Content("~/images/logo.png")" class="ftco-animate" alt="Girl in a jacket" style="height: 80px; width: 80px;">
            <div class="pt-2 pl-2 mt-0 heading-section ftco-animate">
                <h2 class="mb-0" style="font-size: 12px; color: #00266B;"><span>National</span></h2>
                <h2 class="mb-0" style="font-size: 12px; color: #00266B;"><span>Institute of</span></h2>
                <h2 class="mb-0" style="font-size: 12px; color: #00266B;"><span>Computer</span> </h2>
                <h2 class="mb-0" style="font-size: 12px; color: #00266B;"><span>Technology</span> </h2>
            </div>
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#ftco-nav" aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="oi oi-menu"></span> Menu
        </button>
        <div class="collapse navbar-collapse" id="ftco-nav">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item active"><a href="/" class="nav-link pl-0">Home</a></li>
                <li class="nav-item">@Html.ActionLink("Course", "Index", "Course", null,new {@class="nav-link" })</li>
                <li class="nav-item">@Html.ActionLink("Affilation", "Index", "Affilation", null, new { @class = "nav-link" })</li>
                <li class="nav-item">@Html.ActionLink("Student Verification", "Index", "StudentVerification", null, new { @class = "nav-link" })</li>
                <li class="nav-item">@Html.ActionLink("Govt Project", "Index", "GovtProject", null, new { @class = "nav-link" })</li>
                <li class="nav-item">@Html.ActionLink("Gellary", "Gallery", "Home", null, new { @class = "nav-link" })</li>
                <li class="nav-item">@Html.ActionLink("Our Center", "Index", "OurCenter", null, new { @class = "nav-link" })</li>
                <li class="nav-item">@Html.ActionLink("Contact Us", "Index", "Contact", null, new { @class = "nav-link" })</li>
            </ul>
        </div>
    </div>
</nav>
<!-- END nav -->

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - NICTProject</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">NICTProject</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - NICTProject - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

Views/Shared/_Layout1.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <title>@ViewData["Title"] Krishna Institute</title>

    <link href="https://fonts.googleapis.com/css?family=Work+Sans:100,200,300,400,500,600,700,800,900" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Fredericka+the+Great" rel="stylesheet">

    <link rel="stylesheet" href="@Url.Content("~/css/open-iconic-bootstrap.min.css")">
    <link rel="stylesheet" href="@Url.Content("~/css/animate.css")">

    <link rel="stylesheet" href="@Url.Content("~/css/owl.carousel.min.css")">
    <link rel="stylesheet" href="@Url.Content("~/css/owl.theme.default.min.css")">
    <link rel="stylesheet" href="@Url.Content("~/css/magnific-popup.css")">

    <link rel="stylesheet" href="@Url.Content("~/css/aos.css")">

    <link rel="stylesheet" href="@Url.Content("~/css/ionicons.min.css")">

    <link rel="stylesheet" href="@Url.Content("~/css/flaticon.css")">
    <link rel="stylesheet" href="@Url.Content("~/css/icomoon.css")">
    <link rel="stylesheet" href="@Url.Content("~/css/style.css")">

    @*<link rel="stylesheet" href="@Url.Content("~/lib/bootstrap/dist/css/bootstrap.min.css")" />
        <link rel="stylesheet" href="@Url.Content("~/css/site.css")" />*@
</head>
<body>

    <partial name="_Header" />
    @RenderBody()
    <partial name="_Footer" />

    <!-- loader -->
    <div id="ftco-loader" class="show fullscreen"><svg class="circular" width="48px" height="48px"><circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee" /><circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10" stroke="#F96D00" /></svg></div>

    <script src="@Url.Content("~/js/jquery.min.js")"></script>
    <script src="@Url.Content("~/js/jquery-migrate-3.0.1.min.js")"></script>
    <script src="@Url.Content("~/js/popper.min.js")"></script>
    <script src="@Url.Content("~/js/bootstrap.min.js")"></script>
    <script src="@Url.Content("~/js/jquery.easing.1.3.js")"></script>
    <script src="@Url.Content("~/js/jquery.waypoints.min.js")"></script>
    <script src="@Url.Content("~/js/jquery.stellar.min.js")"></script>
    <script src="@Url.Content("~/js/owl.carousel.min.js")"></script>
    <script src="@Url.Content("~/js/jquery.magnific-popup.min.js")"></script>
    <script src="@Url.Content("~/js/aos.js")"></script>
    <script src="@Url.Content("~/js/jquery.animateNumber.min.js")"></script>
    <script src="@Url.Content("~/js/scrollax.min.js")"></script>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBVWaKrjvy3MaE7SQ74_uJiULgl1JY0H2s&sensor=false"></script>
    <script src="@Url.Content("~/js/google-map.js")"></script>
    <script src="@Url.Content("~/js/main.js")"></script>

    @*<script src="@Url.Content("~/lib/jquery/dist/jquery.min.js")"></script>
        <script src="@Url.Content("~/lib/bootstrap/dist/js/bootstrap.bundle.min.js")"></script>
        <script src="@Url.Content("~/js/site.js")" asp-append-version="true"></script>*@
    @RenderSection("Scripts", required: false)
</body>
</html>

Views/Shared/_Slider.cshtml
<section class="home-slider owl-carousel mt-1" style="height: 550px;">
    <div class="slider-item" style="background-image:url('@Url.Content("~/images/bg_1.jpg")');">
        <div class="overlay"></div>
        <div class="container">
            <div class="row no-gutters slider-text align-items-center justify-content-center" data-scrollax-parent="true">
                <div class="col-md-8 text-center ftco-animate">
                    <!-- <h1 class="mb-4">Kids Are The Best <span>Explorers In The World</span></h1>
                    <p><a href="#" class="btn btn-secondary px-4 py-3 mt-3">Read More</a></p> -->
                </div>
            </div>
        </div>
    </div>

    <div class="slider-item" style="background-image:url('@Url.Content("~/images/bg_2.jpg")');">
        <div class="overlay"></div>
        <div class="container">
            <div class="row no-gutters slider-text align-items-center justify-content-center" data-scrollax-parent="true">
                <div class="col-md-8 text-center ftco-animate">
                    <!-- <h1 class="mb-4">Perfect Learned<span> For Your Child</span></h1>
                    <p><a href="#" class="btn btn-secondary px-4 py-3 mt-3">Read More</a></p> -->
                </div>
            </div>
        </div>
    </div>
</section>