Controllers/StudentVerificationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using NICTProject.Data.StoreProcedure;
using NICTProject.Helper;
using NICTProject.Services;
using NICTProject.ViewModel;

namespace NICTProject.Controllers
{
    public class StudentVerificationController : Controller
    {
        private readonly IDapperServices _idapperservices;

        public StudentVerificationController(IDapperServices idapperServices)
        {
            _idapperservices = idapperServices;
        }

        public IActionResult Index()
        {
            HomePageViewModel ViewModelHomePage = new HomePageViewModel();
            ViewModelHomePage.News = _idapperservices.GetNewsAndEvents(new GetEvents() { });
            return View(ViewModelHomePage);
        }

        [HttpPost]
        public IActionResult StudentVerify(string EnrollmentNo)
        {
            AjaxResult response = new AjaxResult();
            response.Data = _idapperservices.GetStudentDetails(new GetStudentDetails() {Id = EnrollmentNo, BranchId = 0 });
            return Json(response);
        }
    }
}

Views/StudentVerification/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

<script>
    function serchStudent(form) {
        var EnrollmentNo = $('#EnrollmentNo').val();
        var formData = new FormData();
        formData.append("EnrollmentNo", EnrollmentNo);
            $.ajax({
                type: 'POST',
                url: '@Url.Action("StudentVerify", "StudentVerification")',
                data: formData,
                processData: false,
                contentType: false,
                success: function (response) {
                    alert('Done');
                }
            })
    }
</script>


<section class="ftco-section ftco-counter img mt-2" id="section-counter" style="background-image: url('@Url.Content("~/images/bg_3.jpg")');" data-stellar-background-ratio="0.5">
    <div class="container mt-0 pt-0">
        <div class="row d-md-flex align-items-center justify-content-center">
            <div class="col-lg-6" style="background-color: #3faaf1; opacity: 0.9; border-radius: 3%;">
                <div class="row justify-content-center mb-0 pb-0 mt-0">
                    <div class="col-md-8 text-center heading-section heading-section-black ftco-animate">
                        <h3 class="mb-2 mt-2 font-weight-bold" style="font-size: 32px; color: aliceblue;">Student Verification </h3>
                    </div>
                </div>
                <form action="#" class="appointment-form ftco-animate p-4">
                    <div class="d-md-flex">
                        <div class="form-group">
                            <input type="text" class="form-control" placeholder="Enrollment No/ Certificate no" id="EnrollmentNo">
                        </div>
                    </div>
                    <div class="d-md-flex align-items-center justify-content-center mt-3">
                        <div class="form-group col-md-7">
                            <input type="button" class="btn btn-warning mr-2" onclick="serchStudent(this)" value="Submit" />
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</section>


<section class="ftco-section ftco-counter img mt-2" id="section-counter"
         style="background-image: url('@Url.Content("~/images/bg_3.jpg")');" data-stellar-background-ratio="0.5">
    <div class="container mt-0 pt-0">
        <div class="row d-md-flex align-items-center justify-content-center">
            <div class="col-lg-5" style="background-color: #3faaf1; opacity: 0.9; border-radius: 0%; height: 400px;">
                <div class="row justify-content-center mb-0 pb-0 mt-0">
                    <div class="col-md-12 text-center heading-section heading-section-black ftco-animate">
                        <h3 class="mb-2 mt-5 font-weight-bold" style="font-size: 32px; color: aliceblue;">
                            Student
                            Verification
                        </h3>
                    </div>
                </div>
                <form action="#" class="appointment-form ftco-animate p-4">
                    <div class="d-md-flex">
                        <div class="form-group">
                            <input type="text" class="form-control" placeholder="Enrollment No/ Certificate no">
                        </div>
                    </div>
                    <div class="d-md-flex align-items-center justify-content-center mt-5">
                        <div class="form-group col-md-7">
                            <button type="button" value="Submit" class="btn btn-warning mr-2">Submit</button>
                            <!-- <input type="submit" value="Submit" class="btn btn-secondary py-3 px-4"> -->
                        </div>
                    </div>
                </form>
            </div>
            <div class="col-lg-5 ml-1" style="background-color: #3faaf1; opacity: 0.9; border-radius: 0%; height: 400px;">
                <div class="row justify-content-center mb-0 pb-0 mt-0">
                    <div class="col-md-12 mt-5 text-center heading-section heading-section-black ftco-animate">
                        <img src="@Url.Content("~/images/account-icon.png")" alt="Girl in a jacket" style="height: 160px; width: 160px;">
                    </div>
                </div>
                <section class="ftco-section ftco-no-pt ftc-no-pb mt-5">
                    <div class="container">
                        <div class="row justify-content-center">
                            <div class="col-md-10 wrap-about py-5 pr-md-4 ftco-animate" style="color: white;">
                                <p>
                                    <span class="" style="font-size: 18px;">Name : </span>Abir Patel <br />
                                    <span class="" style="font-size: 18px;">Enroll No. : </span>1234321 <br />
                                    <span class="" style="font-size: 18px;">Certificate No. : </span>1234321 <br />
                                </p>
                            </div>
                        </div>
                    </div>
                </section>
            </div>
        </div>
    </div>
</section>